---
abstract: 'Routines for converting decimal lat/lon to Google Map tiles, and back again.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Simple: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Coordinates-GMap
requires:
  Exporter: 5.57
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Geo-Coordinates-GMap
  repository: git://github.com/bluefeet/Geo-Coordinates-GMap.git
version: 0.05
